##  A Quick Review from W1

Before pulling any data, we've gotta import all the packages we need

In [5]:
import pandas as pd
import numpy as np

Now we can read in the data from a link OR from a file in the same directory

In [6]:
movies = pd.read_csv('imdb.csv')

Take a quick look at the data

In [7]:
movies.head(3)

,movie_title,imdb_score,content_rating,budget,gross,duration,genres,actor_1_name,actor_2_name,actor_3_name,director_name,language,country,aspect_ratio,title_year
0,Avatar,7.9,PG-13,237000000.0,760505847.0,178.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Joel David Moore,Wes Studi,James Cameron,English,USA,1.78,2009.0
1,Pirates of the Caribbean: At World's End,7.1,PG-13,300000000.0,309404152.0,169.0,Action|Adventure|Fantasy,Johnny Depp,Orlando Bloom,Jack Davenport,Gore Verbinski,English,USA,2.35,2007.0
2,Spectre,6.8,PG-13,245000000.0,200074175.0,148.0,Action|Adventure|Thriller,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Sam Mendes,English,UK,2.35,2015.0

How many rows are there? Columns?

In [8]:
movies.shape

(5043, 15)

There's a lot of columns, could we get a full list?

In [28]:
movies.columns.values.tolist()

['movie_title',
 'imdb_score',
 'content_rating',
 'budget',
 'gross',
 'duration',
 'genres',
 'actor_1_name',
 'actor_2_name',
 'actor_3_name',
 'director_name',
 'language',
 'country',
 'aspect_ratio',
 'title_year']

# Pandas Foundations

## Dataframe who?

Think of dataframes as little "spreadsheets" that hold our data.
<br>Each row represents an observation, and each column represents some feature about that data.

<br> With little bits of code, we can modify what that spreadsheet looks like.
<br> For example, our raw data `movies` can be transformed to show some metric about some feature for some subset of the data

In [23]:
# For example:
movies[movies.country.isin(['USA','France','UK'])].groupby('country')[['gross', 'budget']].agg(['median','max'])

              gross                   budget
             median          max      median          max
country
France    4291965.0  145000989.0  19715000.0  390000000.0
UK       13401683.0  362645141.0  15000000.0  250000000.0
USA      32178777.0  760505847.0  20000000.0  300000000.0

## Series vs. Dataframes

We've been referring to *2 dimensional* tables using the `pd.DataFrame` object
<br>An individual column (or row), is *1 dimensional*. We call this a `pd.Series` object

In [8]:
type(movies)

pandas.core.frame.DataFrame

We can access a series (always 1-dimensional) using either: `df.column` OR `df['column']`

In [11]:
print(type(movies.imdb_score))
print(movies.imdb_score)

<class 'pandas.core.series.Series'>
0       7.9
1       7.1
2       6.8
3       8.5
4       7.1
       ...
5038    7.7
5039    7.5
5040    6.3
5041    6.3
5042    6.6
Name: imdb_score, Length: 5043, dtype: float64

In [12]:
print(type(movies['imdb_score']))
print(movies['imdb_score'])

<class 'pandas.core.series.Series'>
0       7.9
1       7.1
2       6.8
3       8.5
4       7.1
       ...
5038    7.7
5039    7.5
5040    6.3
5041    6.3
5042    6.6
Name: imdb_score, Length: 5043, dtype: float64

To select a **row** as a series, we can use `df.iloc[]` and a specific row number (its index)

In [14]:
print(type(movies.iloc[3]))
movies.iloc[3]

<class 'pandas.core.series.Series'>

movie_title       The Dark Knight Rises
imdb_score                           8.5
content_rating                     PG-13
budget                           2.5e+08
gross                        4.48131e+08
duration                             164
genres                   Action|Thriller
actor_1_name                   Tom Hardy
actor_2_name              Christian Bale
actor_3_name        Joseph Gordon-Levitt
director_name          Christopher Nolan
language                         English
country                              USA
aspect_ratio                        2.35
title_year                          2012
Name: 3, dtype: object

## Subsetting Columns

Subsetting and filtering is one of the most important, yet confusing topics when getting started.
<br>As we go along, feel free to run the code part by part to see what's going on in each step. `type()` is also a great tool here

Lets take a look at a smaller set of columns, say the movie title, actors & director name

In [13]:
movies[['movie_title','actor_1_name','actor_2_name','actor_3_name','director_name']] # Note TWO square brackets

,movie_title,actor_1_name,actor_2_name,actor_3_name,director_name
0,Avatar,CCH Pounder,Joel David Moore,Wes Studi,James Cameron
1,Pirates of the Caribbean: At World's End,Johnny Depp,Orlando Bloom,Jack Davenport,Gore Verbinski
2,Spectre,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Sam Mendes
3,The Dark Knight Rises,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Christopher Nolan
4,Star Wars: Episode VII - The Force Awakens ...,Doug Walker,Rob Walker,NaN,Doug Walker
...,...,...,...,...,...
5038,Signed Sealed Delivered,Eric Mabius,Daphne Zuniga,Crystal Lowe,Scott Smith
5039,The Following,Natalie Zea,Valorie Curry,Sam Underwood,NaN
5040,A Plague So Pleasant,Eva Boehnke,Maxwell Moody,David Chandler,Benjamin Roberds
5041,Shanghai Calling,Alan Ruck,Daniel Henney,Eliza Coupe,Daniel Hsia
5042,My Date with Drew,John August,Brian Herzlinger,Jon Gunn,Jon Gunn

Side Note: Why did we use two square brackets? What we're doing is passing a `list` to the subset function.
<br> Pandas `DataFrame` objects know that whenever we place `[]` after it, we're looking to do some sort of filtering operation

In [15]:
actor_cols = ['actor_1_name','actor_2_name','actor_3_name']
movies[actor_cols]

         actor_1_name      actor_2_name          actor_3_name
0         CCH Pounder  Joel David Moore             Wes Studi
1         Johnny Depp     Orlando Bloom        Jack Davenport
2     Christoph Waltz      Rory Kinnear      Stephanie Sigman
3           Tom Hardy    Christian Bale  Joseph Gordon-Levitt
4         Doug Walker        Rob Walker                   NaN
...               ...               ...                   ...
5038      Eric Mabius     Daphne Zuniga          Crystal Lowe
5039      Natalie Zea     Valorie Curry         Sam Underwood
5040      Eva Boehnke     Maxwell Moody        David Chandler
5041        Alan Ruck     Daniel Henney           Eliza Coupe
5042      John August  Brian Herzlinger              Jon Gunn

[5043 rows x 3 columns]

Another quick point of confusion: Check out the difference between `df['column']` vs `df[['column']]` ( try it out below)

In [15]:
movies['content_rating']

0       PG-13
1       PG-13
2       PG-13
3       PG-13
4         NaN
        ...
5038      NaN
5039    TV-14
5040      NaN
5041    PG-13
5042       PG
Name: content_rating, Length: 5043, dtype: object

In [16]:
movies[['content_rating']]

     content_rating
0             PG-13
1             PG-13
2             PG-13
3             PG-13
4               NaN
...             ...
5038            NaN
5039          TV-14
5040            NaN
5041          PG-13
5042             PG

[5043 rows x 1 columns]

The former creates a *series*, since the input is just one *string*. The latter creates a *dataframe*, since the input is a *list* of columns.

## Filtering Rows With Conditions

Another common task is to filter rows based upon some criteria we have. We could:
1. Compare floats
2. Match strings
3. Check against multiple elements

In [17]:
movies[movies.imdb_score > 8]

,movie_title,imdb_score,content_rating,budget,gross,duration,genres,actor_1_name,actor_2_name,actor_3_name,director_name,language,country,aspect_ratio,title_year
3,The Dark Knight Rises,8.5,PG-13,250000000.0,448130642.0,164.0,Action|Thriller,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Christopher Nolan,English,USA,2.35,2012.0
17,The Avengers,8.1,PG-13,220000000.0,623279547.0,173.0,Action|Adventure|Sci-Fi,Chris Hemsworth,Robert Downey Jr.,Scarlett Johansson,Joss Whedon,English,USA,1.85,2012.0
27,Captain America: Civil War,8.2,PG-13,250000000.0,407197282.0,147.0,Action|Adventure|Sci-Fi,Robert Downey Jr.,Scarlett Johansson,Chris Evans,Anthony Russo,English,USA,2.35,2016.0
43,Toy Story 3,8.3,G,200000000.0,414984497.0,103.0,Adventure|Animation|Comedy|Family|Fantasy,Tom Hanks,John Ratzenberger,Don Rickles,Lee Unkrich,English,USA,1.85,2010.0
58,WALL·E,8.4,G,180000000.0,223806889.0,98.0,Adventure|Animation|Family|Sci-Fi,John Ratzenberger,Fred Willard,Jeff Garlin,Andrew Stanton,English,USA,2.35,2008.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4924,Butterfly Girl,8.7,NaN,180000.0,NaN,78.0,Documentary,Abigail Evans,Stacie Evans,Emily Gorell,Cary Bell,English,USA,NaN,2014.0
4937,A Charlie Brown Christmas,8.4,TV-G,150000.0,NaN,25.0,Animation|Comedy|Family,Peter Robbins,Bill Melendez,Christopher Shea,Bill Melendez,English,USA,1.33,1965.0
4945,The Brain That Sings,8.2,NaN,125000.0,NaN,62.0,Documentary|Family,NaN,NaN,NaN,Amal Al-Agroobi,Arabic,United Arab Emirates,NaN,2013.0
4972,"Peace, Propaganda & the Promised Land",8.3,NaN,70000.0,NaN,80.0,Documentary,Noam Chomsky,Seth Ackerman,Arik Ascherman,Sut Jhally,English,USA,NaN,2004.0
5001,The Last Waltz,8.2,PG,NaN,321952.0,117.0,Documentary|Music,Ringo Starr,Levon Helm,Bob Dylan,Martin Scorsese,English,USA,1.85,1978.0

In [70]:
movies[movies.content_rating == 'G']

,movie_title,imdb_score,content_rating,budget,gross,duration,genres,actor_1_name,actor_2_name,actor_3_name,director_name,language,country,aspect_ratio,title_year
35,Monsters University,7.3,G,200000000.0,268488329.0,104.0,Adventure|Animation|Comedy|Family|Fantasy,Steve Buscemi,Tyler Labine,Sean Hayes,Dan Scanlon,English,USA,1.85,2013.0
41,Cars 2,6.3,G,200000000.0,191450875.0,106.0,Adventure|Animation|Comedy|Family|Sport,Joe Mantegna,Thomas Kretschmann,Eddie Izzard,John Lasseter,English,USA,2.35,2011.0
43,Toy Story 3,8.3,G,200000000.0,414984497.0,103.0,Adventure|Animation|Comedy|Family|Fantasy,Tom Hanks,John Ratzenberger,Don Rickles,Lee Unkrich,English,USA,1.85,2010.0
58,WALL·E,8.4,G,180000000.0,223806889.0,98.0,Adventure|Animation|Family|Sci-Fi,John Ratzenberger,Fred Willard,Jeff Garlin,Andrew Stanton,English,USA,2.35,2008.0
91,The Polar Express,6.6,G,165000000.0,665426.0,100.0,Adventure|Animation|Family|Fantasy,Tom Hanks,Eddie Deezen,Peter Scolari,Robert Zemeckis,English,USA,2.35,2004.0
119,Ratatouille,8.0,G,150000000.0,206435493.0,111.0,Animation|Comedy|Family|Fantasy,Janeane Garofalo,John Ratzenberger,Brian Dennehy,Brad Bird,English,USA,2.35,2007.0
209,Rio 2,6.4,G,103000000.0,131536019.0,101.0,Adventure|Animation|Comedy|Family|Musical,Miguel Ferrer,Rachel Crow,Jeffrey Garcia,Carlos Saldanha,English,USA,2.35,2014.0
238,"Monsters, Inc.",8.1,G,115000000.0,289907418.0,92.0,Adventure|Animation|Comedy|Family|Fantasy,Steve Buscemi,John Ratzenberger,James Coburn,Pete Docter,English,USA,1.85,2001.0
277,The Princess and the Frog,7.1,G,105000000.0,104374107.0,97.0,Animation|Family|Fantasy|Musical|Romance,Oprah Winfrey,Jenifer Lewis,Anika Noni Rose,Ron Clements,English,USA,1.85,2009.0
297,The Hunchback of Notre Dame,6.9,G,100000000.0,100117603.0,91.0,Animation|Drama|Family|Musical|Romance,Demi Moore,Jason Alexander,Bill Fagerbakke,Gary Trousdale,English,USA,1.78,1996.0
298,The Emperor's New Groove,7.3,G,100000000.0,89296573.0,78.0,Adventure|Animation|Comedy|Family|Fantasy,Eartha Kitt,Wendie Malick,John Fiedler,Mark Dindal,English,USA,1.66,2000.0
323,The Peanuts Movie,7.2,G,99000000.0,130174897.0,88.0,Adventure|Animation|Comedy|Family,Francesca Capaldi,Venus Schultheis,Bill Melendez,Steve Martino,English,USA,1.85,2015.0
338,Finding Nemo,8.2,G,94000000.0,380838870.0,100.0,Adventure|Animation|Comedy|Family,Alexander Gould,Stephen Root,Brad Garrett,Andrew Stanton,English,USA,1.85,2003.0
353,Toy Story 2,7.9,G,90000000.0,245823397.0,82.0,Adventure|Animation|Comedy|Family|Fantasy,Tom Hanks,John Ratzenberger,Wayne Knight,John Lasseter,English,USA,1.85,1999.0
362,Mulan,7.5,G,90000000.0,120618403.0,88.0,Adventure|Animation|Family|Fantasy|Musical|War,Ming-Na Wen,Harvey Fierstein,June Foray,Tony Bancroft,English,USA,1.66,1998.0
384,Rio,7.0,G,90000000.0,143618384.0,96.0,Adventure|Animation|Comedy|Family|Musical,Anne Hathaway,Wanda Sykes,Will.i.am,Carlos Saldanha,English,USA,2.35,2011.0
406,102 Dalmatians,4.8,G,85000000.0,66941559.0,100.0,Adventure|Comedy|Family,Ioan Gruffudd,Eric Idle,Jim Carter,Kevin Lima,English,USA,1.85,2000.0
444,Charlotte's Web,6.4,G,NaN,82506325.0,97.0,Comedy|Family|Fantasy,Steve Buscemi,Julia Roberts,Oprah Winfrey,Gary Winick,English,USA,1.85,2006.0
448,Alvin and the Chipmunks: Chipwrecked,4.4,G,75000000.0,133103929.0,87.0,Adventure|Animation|Comedy|Family|Fantasy|Music,Amy Poehler,Jesse McCartney,Lauren Gottlieb,Mike Mitchell,English,USA,1.85,2011.0
473,Spirit: Stallion of the Cimarron,7.0,G,80000000.0,73215310.0,83.0,Adventure|Animation|Family|Western,Matt Damon,Charles Napier,Zahn McClarnon,Kelly Asbury,English,USA,2.35,2002.0
480,Fantasia 2000,7.3,G,80000000.0,60507228.0,74.0,Animation|Family|Fantasy|Music,Quincy Jones,Penn Jillette,Russi Taylor,James Algar,English,USA,1.78,1999.0
500,Babe: Pig in the City,5.8,G,80000000.0,18318000.0,97.0,Adventure|Comedy|Drama|Family|Fantasy,Adam Goldberg,Elizabeth Daily,Glenne Headly,George Miller,English,Australia,1.85,1998.0
504,Oceans,7.8,G,40000000.0,19406406.0,104.0,Documentary|Drama,Pedro Armendáriz Jr.,Jacques Perrin,Rie Miyazawa,Jacques Perrin,French,France,2.35,2009.0
509,The Lion King,8.5,G,45000000.0,422783777.0,73.0,Adventure|Animation|Drama|Family|Musical,Matthew Broderick,Nathan Lane,Niketa Calame,Roger Allers,English,USA,1.66,1994.0
583,Cars,7.2,G,120000000.0,244052771.0,117.0,Adventure|Animation|Comedy|Family|Sport,John Ratzenberger,Cheech Marin,George Carlin,John Lasseter,English,USA,2.35,2006.0
657,The Santa Clause 2,5.5,G,60000000.0,139225854.0,104.0,Comedy|Family|Fantasy,Judge Reinhold,Aisha Tyler,Eric Lloyd,Michael Lembeck,English,USA,1.85,2002.0
714,Chicken Little,5.8,G,150000000.0,135381507.0,81.0,Adventure|Animation|Comedy|Family|Sci-Fi,Catherine O'Hara,Fred Willard,Amy Sedaris,Mark Dindal,English,USA,1.85,2005.0
756,The Tale of Despereaux,6.1,G,60000000.0,50818750.0,93.0,Adventure|Animation|Comedy|Family|Fantasy,Emma Watson,Matthew Broderick,Frank Langella,Sam Fell,English,UK,2.35,2008.0
839,Pocahontas,6.6,G,55000000.0,141600000.0,84.0,Adventure|Animation|Drama|Family|History|Music...,Christian Bale,Frank Welker,Irene Bedard,Mike Gabriel,English,USA,1.78,1995.0
902,Anastasia,7.1,G,50000000.0,58297830.0,94.0,Adventure|Animation|Drama|Family|Fantasy|Music...,Kirsten Dunst,Kelsey Grammer,Bernadette Peters,Don Bluth,English,USA,2.35,1997.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2913,The Land Before Time,7.3,G,12500000.0,48092846.0,69.0,Adventure|Animation|Family,Judith Barsi,Gabriel Damon,Bill Erwin,Don Bluth,English,USA,1.33,1988.0
2943,The Muppet Christmas Carol,7.7,G,12000000.0,27281507.0,89.0,Comedy|Drama|Family|Fantasy|Musical,Steven Mackintosh,Jerry Nelson,Steve Whitmire,Brian Henson,English,USA,1.85,1992.0
3028,High School Musical 3: Senior Year,4.5,G,11000000.0,90556401.0,112.0,Comedy|Drama|Family|Music|Musical|Romance,Lucas Grabeel,Matt Prokop,Corbin Bleu,Kenny Ortega,English,USA,1.85,2008.0
3079,2001: A Space Odyssey,8.3,G,12000000.0,56715371.0,161.0,Adventure|Mystery|Sci-Fi,Keir Dullea,Gary Lockwood,Glenn Beck,Stanley Kubrick,English,UK,2.20,1968.0
3101,The Longest Day,7.8,G,10000000.0,NaN,178.0,Action|Drama|History|War,Richard Burton,Richard Beymer,Eddie Albert,Ken Annakin,English,USA,2.35,1962.0
3107,Oliver!,7.5,G,10000000.0,16800000.0,153.0,Drama|Family|Musical,Oliver Reed,Ron Moody,Jack Wild,Carol Reed,English,UK,2.35,1968.0
3109,Recess: School's Out,6.5,G,23000000.0,36696761.0,82.0,Animation|Comedy|Family|Mystery|Sci-Fi,Diedrich Bader,Andrew Lawrence,Dabney Coleman,Chuck Sheetz,English,USA,1.85,2001.0
3142,Kit Kittredge: An American Girl,6.7,G,10000000.0,17655201.0,101.0,Drama|Family,Julia Ormond,Jane Krakowski,Willow Smith,Patricia Rozema,English,USA,1.85,2008.0
3179,The Straight Story,8.0,G,10000000.0,6197866.0,112.0,Biography|Drama,Sissy Spacek,Richard Farnsworth,Everett McGill,David Lynch,English,France,2.35,1999.0
3280,Fiddler on the Roof,8.0,G,9000000.0,50000000.0,181.0,Drama|Family|Musical|Romance,Topol,Paul Michael Glaser,Rosalind Harris,Norman Jewison,English,USA,2.35,1971.0
3356,The Muppet Movie,7.7,G,NaN,76657000.0,95.0,Adventure|Comedy|Family|Musical,Madeline Kahn,Jim Henson,Dom DeLuise,James Frawley,English,UK,1.85,1979.0
3359,The Sound of Music,8.0,G,8200000.0,163214286.0,174.0,Biography|Drama|Family|Musical|Romance,Eleanor Parker,Angela Cartwright,Nicholas Hammond,Robert Wise,English,USA,2.35,1965.0
3518,The Mighty Macs,6.5,G,7000000.0,1889522.0,99.0,Drama|Sport,Ellen Burstyn,Marley Shelton,Jennifer Butler,Tim Chambers,English,USA,2.35,2009.0
3563,The Andromeda Strain,7.2,G,6500000.0,NaN,115.0,Sci-Fi|Thriller,David Wayne,Paula Kelly,Eric Christmas,Robert Wise,English,USA,2.35,1971.0
3708,The Return of the Pink Panther,7.1,G,5000000.0,NaN,113.0,Comedy|Crime|Mystery,Burt Kwouk,Herbert Lom,Catherine Schell,Blake Edwards,English,UK,2.35,1975.0
3723,Doug's 1st Movie,5.0,G,5000000.0,19421271.0,77.0,Animation|Comedy|Family,Frank Welker,Constance Shulman,Alice Playten,Maurice Joyce,English,USA,1.33,1999.0
3970,Gone with the Wind,8.2,G,3977000.0,198655278.0,226.0,Drama|History|Romance|War,Hattie McDaniel,George Reeves,Thomas Mitchell,Victor Fleming,English,USA,1.37,1939.0
4024,March of the Penguins,7.6,G,8000000.0,77413017.0,80.0,Documentary,Morgan Freeman,Sofie Gråbøl,Romane Bohringer,Luc Jacquet,French,France,1.85,2005.0
4062,Beneath the Planet of the Apes,6.1,G,3000000.0,NaN,95.0,Action|Adventure|Sci-Fi,Linda Harrison,Gregory Sierra,Victor Buono,Ted Post,English,USA,2.35,1970.0
4064,Pokémon 3: The Movie,5.6,G,16000000.0,NaN,93.0,Action|Adventure|Animation|Family|Fantasy|Sci-Fi,Veronica Taylor,Eric Stuart,Lisa Ortiz,Kunihiko Yuyama,Japanese,Japan,1.85,2000.0
4093,Willy Wonka & the Chocolate Factory,7.8,G,3000000.0,NaN,89.0,Family|Fantasy|Musical,Peter Ostrum,Jack Albertson,Julie Dawn Cole,Mel Stuart,English,USA,1.33,1971.0
4162,The Black Stallion,7.4,G,2700000.0,NaN,118.0,Adventure|Family|Sport,Teri Garr,Kelly Reno,Hoyt Axton,Carroll Ballard,English,USA,1.85,1979.0
4185,Escape from the Planet of the Apes,6.3,G,2500000.0,NaN,98.0,Action|Sci-Fi,Roddy McDowall,M. Emmet Walsh,Sal Mineo,Don Taylor,English,USA,2.35,1971.0
4225,Fantasia,7.8,G,2280000.0,76400000.0,120.0,Animation|Family|Fantasy|Music,Leopold Stokowski,Deems Taylor,NaN,James Algar,English,USA,1.37,1940.0
4362,Battle for the Planet of the Apes,5.5,G,1800000.0,NaN,96.0,Action|Sci-Fi,Roddy McDowall,Paul Williams,Claude Akins,J. Lee Thompson,English,USA,2.35,1973.0
4427,Modern Times,8.6,G,1500000.0,163245.0,87.0,Comedy|Drama|Family,Paulette Goddard,Stanley Blystone,Fred Malatesta,Charles Chaplin,English,USA,1.37,1936.0
4591,A Lego Brickumentary,6.8,G,1000000.0,100240.0,93.0,Documentary,G.W. Krauss,Brian Whitaker,Jason Bateman,Kief Davidson,English,Denmark,NaN,2014.0
4725,Benji,6.1,G,500000.0,39552600.0,86.0,Adventure|Family|Romance,Frances Bavier,Peter Breck,Edgar Buchanan,Joe Camp,English,USA,1.85,1974.0
4787,Rise of the Entrepreneur: The Search for a Bet...,8.2,G,450000.0,NaN,52.0,Documentary,Bob Proctor,Jack Canfield,Eric Worre,Joe Kenemore,English,USA,NaN,2014.0
4874,Sunday School Musical,2.5,G,NaN,NaN,93.0,Drama|Musical,Dustin Fitzsimons,Mark Hengst,Debra Lynn Hull,Rachel Goldenberg,English,USA,1.85,2008.0

What if we wanted to find movies that were either `G`, `PG`, or `PG-13`? 
We'd have to type out something pretty annoying like: 
```python
movies[(movies.content_rating == 'G') | (movies.content_rating == 'PG') | (movies.content_rating == 'PG-13')]
```

<br>Instead, we'll use the `.isin()` operator to match against a group. Remember, `.isin()` accepts a `list` only

In [69]:
movies[movies.content_rating.isin(['G','PG', 'PG-13'])]

,movie_title,imdb_score,content_rating,budget,gross,duration,genres,actor_1_name,actor_2_name,actor_3_name,director_name,language,country,aspect_ratio,title_year
0,Avatar,7.9,PG-13,237000000.0,760505847.0,178.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Joel David Moore,Wes Studi,James Cameron,English,USA,1.78,2009.0
1,Pirates of the Caribbean: At World's End,7.1,PG-13,300000000.0,309404152.0,169.0,Action|Adventure|Fantasy,Johnny Depp,Orlando Bloom,Jack Davenport,Gore Verbinski,English,USA,2.35,2007.0
2,Spectre,6.8,PG-13,245000000.0,200074175.0,148.0,Action|Adventure|Thriller,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Sam Mendes,English,UK,2.35,2015.0
3,The Dark Knight Rises,8.5,PG-13,250000000.0,448130642.0,164.0,Action|Thriller,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Christopher Nolan,English,USA,2.35,2012.0
5,John Carter,6.6,PG-13,263700000.0,73058679.0,132.0,Action|Adventure|Sci-Fi,Daryl Sabara,Samantha Morton,Polly Walker,Andrew Stanton,English,USA,2.35,2012.0
6,Spider-Man 3,6.2,PG-13,258000000.0,336530303.0,156.0,Action|Adventure|Romance,J.K. Simmons,James Franco,Kirsten Dunst,Sam Raimi,English,USA,2.35,2007.0
7,Tangled,7.8,PG,260000000.0,200807262.0,100.0,Adventure|Animation|Comedy|Family|Fantasy|Musi...,Brad Garrett,Donna Murphy,M.C. Gainey,Nathan Greno,English,USA,1.85,2010.0
8,Avengers: Age of Ultron,7.5,PG-13,250000000.0,458991599.0,141.0,Action|Adventure|Sci-Fi,Chris Hemsworth,Robert Downey Jr.,Scarlett Johansson,Joss Whedon,English,USA,2.35,2015.0
9,Harry Potter and the Half-Blood Prince,7.5,PG,250000000.0,301956980.0,153.0,Adventure|Family|Fantasy|Mystery,Alan Rickman,Daniel Radcliffe,Rupert Grint,David Yates,English,UK,2.35,2009.0
10,Batman v Superman: Dawn of Justice,6.9,PG-13,250000000.0,330249062.0,183.0,Action|Adventure|Sci-Fi,Henry Cavill,Lauren Cohan,Alan D. Purwin,Zack Snyder,English,USA,2.35,2016.0
11,Superman Returns,6.1,PG-13,209000000.0,200069408.0,169.0,Action|Adventure|Sci-Fi,Kevin Spacey,Marlon Brando,Frank Langella,Bryan Singer,English,USA,2.35,2006.0
12,Quantum of Solace,6.7,PG-13,200000000.0,168368427.0,106.0,Action|Adventure,Giancarlo Giannini,Mathieu Amalric,Rory Kinnear,Marc Forster,English,UK,2.35,2008.0
13,Pirates of the Caribbean: Dead Man's Chest,7.3,PG-13,225000000.0,423032628.0,151.0,Action|Adventure|Fantasy,Johnny Depp,Orlando Bloom,Jack Davenport,Gore Verbinski,English,USA,2.35,2006.0
14,The Lone Ranger,6.5,PG-13,215000000.0,89289910.0,150.0,Action|Adventure|Western,Johnny Depp,Ruth Wilson,Tom Wilkinson,Gore Verbinski,English,USA,2.35,2013.0
15,Man of Steel,7.2,PG-13,225000000.0,291021565.0,143.0,Action|Adventure|Fantasy|Sci-Fi,Henry Cavill,Christopher Meloni,Harry Lennix,Zack Snyder,English,USA,2.35,2013.0
16,The Chronicles of Narnia: Prince Caspian,6.6,PG,225000000.0,141614023.0,150.0,Action|Adventure|Family|Fantasy,Peter Dinklage,Pierfrancesco Favino,Damián Alcázar,Andrew Adamson,English,USA,2.35,2008.0
17,The Avengers,8.1,PG-13,220000000.0,623279547.0,173.0,Action|Adventure|Sci-Fi,Chris Hemsworth,Robert Downey Jr.,Scarlett Johansson,Joss Whedon,English,USA,1.85,2012.0
18,Pirates of the Caribbean: On Stranger Tides,6.7,PG-13,250000000.0,241063875.0,136.0,Action|Adventure|Fantasy,Johnny Depp,Sam Claflin,Stephen Graham,Rob Marshall,English,USA,2.35,2011.0
19,Men in Black 3,6.8,PG-13,225000000.0,179020854.0,106.0,Action|Adventure|Comedy|Family|Fantasy|Sci-Fi,Will Smith,Michael Stuhlbarg,Nicole Scherzinger,Barry Sonnenfeld,English,USA,1.85,2012.0
20,The Hobbit: The Battle of the Five Armies,7.5,PG-13,250000000.0,255108370.0,164.0,Adventure|Fantasy,Aidan Turner,Adam Brown,James Nesbitt,Peter Jackson,English,New Zealand,2.35,2014.0
21,The Amazing Spider-Man,7.0,PG-13,230000000.0,262030663.0,153.0,Action|Adventure|Fantasy,Emma Stone,Andrew Garfield,Chris Zylka,Marc Webb,English,USA,2.35,2012.0
22,Robin Hood,6.7,PG-13,200000000.0,105219735.0,156.0,Action|Adventure|Drama|History,Mark Addy,William Hurt,Scott Grimes,Ridley Scott,English,USA,2.35,2010.0
23,The Hobbit: The Desolation of Smaug,7.9,PG-13,225000000.0,258355354.0,186.0,Adventure|Fantasy,Aidan Turner,Adam Brown,James Nesbitt,Peter Jackson,English,USA,2.35,2013.0
24,The Golden Compass,6.1,PG-13,180000000.0,70083519.0,113.0,Adventure|Family|Fantasy,Christopher Lee,Eva Green,Kristin Scott Thomas,Chris Weitz,English,USA,2.35,2007.0
25,King Kong,7.2,PG-13,207000000.0,218051260.0,201.0,Action|Adventure|Drama|Romance,Naomi Watts,Thomas Kretschmann,Evan Parke,Peter Jackson,English,New Zealand,2.35,2005.0
26,Titanic,7.7,PG-13,200000000.0,658672302.0,194.0,Drama|Romance,Leonardo DiCaprio,Kate Winslet,Gloria Stuart,James Cameron,English,USA,2.35,1997.0
27,Captain America: Civil War,8.2,PG-13,250000000.0,407197282.0,147.0,Action|Adventure|Sci-Fi,Robert Downey Jr.,Scarlett Johansson,Chris Evans,Anthony Russo,English,USA,2.35,2016.0
28,Battleship,5.9,PG-13,209000000.0,65173160.0,131.0,Action|Adventure|Sci-Fi|Thriller,Liam Neeson,Alexander Skarsgård,Tadanobu Asano,Peter Berg,English,USA,2.35,2012.0
29,Jurassic World,7.0,PG-13,150000000.0,652177271.0,124.0,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Judy Greer,Omar Sy,Colin Trevorrow,English,USA,2.00,2015.0
30,Skyfall,7.8,PG-13,200000000.0,304360277.0,143.0,Action|Adventure|Thriller,Albert Finney,Helen McCrory,Rory Kinnear,Sam Mendes,English,UK,2.35,2012.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4842,Across the Universe,7.4,PG-13,45000000.0,24343673.0,133.0,Drama|Fantasy|Musical|Romance,Jim Sturgess,T.V. Carpio,Robert Clohessy,Julie Taymor,English,USA,2.35,2007.0
4864,Like Crazy,6.7,PG-13,250000.0,3388210.0,90.0,Drama|Romance,Jennifer Lawrence,Charlie Bewley,Finola Hughes,Drake Doremus,English,USA,1.78,2011.0
4871,Shotgun Stories,7.3,PG-13,NaN,45661.0,92.0,Drama|Thriller,Michael Abbott Jr.,Natalie Canerday,Travis Smith,Jeff Nichols,English,USA,2.35,2007.0
4874,Sunday School Musical,2.5,G,NaN,NaN,93.0,Drama|Musical,Dustin Fitzsimons,Mark Hengst,Debra Lynn Hull,Rachel Goldenberg,English,USA,1.85,2008.0
4875,Rust,5.7,PG,250000.0,NaN,95.0,Drama,Corbin Bernsen,Lorne Cardinal,Kirsten Collins,Corbin Bernsen,English,Canada,1.78,2010.0
4877,The Christmas Bunny,6.2,PG,250000.0,NaN,98.0,Drama|Family,Florence Henderson,Derek Brandon,Charles Irving Beale,Tom Seidman,English,USA,NaN,2010.0
4880,UnDivided,7.8,PG,250000.0,NaN,66.0,Documentary,Sam Adams,Steve Duin,Jeff Jacob,Sam Martin,English,USA,NaN,2013.0
4881,The Frozen,4.4,PG-13,250000.0,NaN,95.0,Horror|Thriller,Noah Segan,Brit Morgan,Sedona James,Andrew Hyatt,English,USA,NaN,2012.0
4883,Horse Camp,6.6,PG,250000.0,NaN,108.0,Family,Joshua Ray Bell,Dana Blackstone,Annelyse Ahmad,Joel Paul Reisig,English,USA,NaN,2014.0
4900,The Grace Card,6.4,PG-13,200000.0,2428241.0,101.0,Drama,Michael Joiner,Chris Thomas,Michael Higgenbottom,David G. Evans,English,USA,NaN,2010.0
4904,Call + Response,7.5,PG-13,200000.0,215185.0,86.0,Documentary|History|Music,Matisyahu,Natasha Bedingfield,Madeleine Albright,Justin Dillon,English,USA,NaN,2008.0
4908,Super Hybrid,3.9,PG-13,13000000.0,NaN,94.0,Horror|Sci-Fi|Thriller,Melanie Papalia,Ryan Kennedy,John Reardon,Eric Valette,English,USA,2.35,2010.0
4915,The Trials of Darryl Hunt,7.7,PG-13,200000.0,1111.0,106.0,Crime|Documentary,Darryl Hunt,Evelyn Jefferson,John Reeves,Ricki Stern,English,USA,1.66,2006.0
4917,Yesterday Was a Lie,5.4,PG,2500000.0,NaN,89.0,Drama|Music|Mystery|Romance|Sci-Fi,John Newton,Chase Masterson,H.M. Wynant,James Kerwin,English,USA,1.78,2008.0
4921,Children of Heaven,8.5,PG,180000.0,925402.0,89.0,Drama|Family,Bahare Seddiqi,Amir Farrokh Hashemian,Mohammad Amir Naji,Majid Majidi,Persian,Iran,1.85,1997.0
4926,Another Earth,7.0,PG-13,100000.0,1316074.0,92.0,Drama|Romance|Sci-Fi,Robin Lord Taylor,William Mapother,Flint Beverage,Mike Cahill,English,USA,1.85,2011.0
4930,Tadpole,6.3,PG-13,150000.0,2882062.0,78.0,Comedy|Drama|Romance,Bebe Neuwirth,Aaron Stanford,Ron Rifkin,Gary Winick,English,USA,1.85,2000.0
4935,Heroes of Dirt,7.1,PG-13,NaN,NaN,98.0,Action|Drama|Sport,Joel Moody,Bill Allen,Lia Tucker,Eric Bugbee,English,USA,NaN,2015.0
4948,Romantic Schemer,5.1,PG-13,125000.0,NaN,NaN,Romance,Diane Sorrentino,Valentine,NaN,Valentine,English,USA,NaN,2015.0
4955,Facing the Giants,6.7,PG,100000.0,10174663.0,111.0,Drama|Sport,Alex Kendrick,Erin Bethea,Shannen Fields,Alex Kendrick,English,USA,1.85,2006.0
4960,The Mighty,7.3,PG-13,NaN,2643689.0,100.0,Comedy|Drama,Kieran Culkin,Elden Henson,Gena Rowlands,Peter Chelsom,English,USA,1.85,1998.0
4962,The Lost Skeleton of Cadavra,7.0,PG,40000.0,110536.0,90.0,Comedy|Horror|Sci-Fi,Fay Masterson,Brian Howe,Larry Blamire,Larry Blamire,English,USA,1.85,2001.0
4963,"Dude, Where's My Dog?!",3.2,PG,20000.0,NaN,82.0,Family,Kevin P. Farley,Gabriela Castillo,Brandon Middleton,Stephen Langford,English,USA,1.85,2014.0
4977,Super Size Me,7.3,PG,65000.0,11529368.0,100.0,Comedy|Documentary|Drama,Chemeeka Walker,Amanda Kearsan,Amelia Giancarlo,Morgan Spurlock,English,USA,1.78,2004.0
4993,The Signal,6.1,PG-13,4000000.0,NaN,97.0,Sci-Fi|Thriller,Lin Shaye,Olivia Cooke,Beau Knapp,William Eubank,English,USA,2.35,2014.0
5001,The Last Waltz,8.2,PG,NaN,321952.0,117.0,Documentary|Music,Ringo Starr,Levon Helm,Bob Dylan,Martin Scorsese,English,USA,1.85,1978.0
5033,Primer,7.0,PG-13,7000.0,424760.0,77.0,Drama|Sci-Fi|Thriller,Shane Carruth,David Sullivan,Casey Gooden,Shane Carruth,English,USA,1.85,2004.0
5036,The Mongol King,7.8,PG-13,3250.0,NaN,84.0,Crime|Drama,Richard Jewell,John Considine,Sara Stepnicka,Anthony Vallone,English,USA,NaN,2005.0
5041,Shanghai Calling,6.3,PG-13,NaN,10443.0,100.0,Comedy|Drama|Romance,Alan Ruck,Daniel Henney,Eliza Coupe,Daniel Hsia,English,USA,2.35,2012.0
5042,My Date with Drew,6.6,PG,1100.0,85222.0,90.0,Documentary,John August,Brian Herzlinger,Jon Gunn,Jon Gunn,English,USA,1.85,2004.0

### Masking

What's going on under the hood? When we say something like this,
```python 
movies.content_rating == 'G'
```
We're actually asking Pandas to check that **for each** row in the series, if the given statement is True or False.

In [42]:
movies.content_rating == 'G'

0       False
1       False
2       False
3       False
4       False
5       False
6       False
7       False
8       False
9       False
10      False
11      False
12      False
13      False
14      False
15      False
16      False
17      False
18      False
19      False
20      False
21      False
22      False
23      False
24      False
25      False
26      False
27      False
28      False
29      False
        ...
5013    False
5014    False
5015    False
5016    False
5017    False
5018    False
5019    False
5020    False
5021    False
5022    False
5023    False
5024    False
5025    False
5026    False
5027    False
5028    False
5029    False
5030    False
5031    False
5032    False
5033    False
5034    False
5035    False
5036    False
5037    False
5038    False
5039    False
5040    False
5041    False
5042    False
Name: content_rating, Length: 5043, dtype: bool

In [43]:
movies[  movies.content_rating == 'G'  ]

,movie_title,imdb_score,content_rating,budget,gross,duration,genres,actor_1_name,actor_2_name,actor_3_name,director_name,language,country,aspect_ratio,title_year
35,Monsters University,7.3,G,200000000.0,268488329.0,104.0,Adventure|Animation|Comedy|Family|Fantasy,Steve Buscemi,Tyler Labine,Sean Hayes,Dan Scanlon,English,USA,1.85,2013.0
41,Cars 2,6.3,G,200000000.0,191450875.0,106.0,Adventure|Animation|Comedy|Family|Sport,Joe Mantegna,Thomas Kretschmann,Eddie Izzard,John Lasseter,English,USA,2.35,2011.0
43,Toy Story 3,8.3,G,200000000.0,414984497.0,103.0,Adventure|Animation|Comedy|Family|Fantasy,Tom Hanks,John Ratzenberger,Don Rickles,Lee Unkrich,English,USA,1.85,2010.0
58,WALL·E,8.4,G,180000000.0,223806889.0,98.0,Adventure|Animation|Family|Sci-Fi,John Ratzenberger,Fred Willard,Jeff Garlin,Andrew Stanton,English,USA,2.35,2008.0
91,The Polar Express,6.6,G,165000000.0,665426.0,100.0,Adventure|Animation|Family|Fantasy,Tom Hanks,Eddie Deezen,Peter Scolari,Robert Zemeckis,English,USA,2.35,2004.0
119,Ratatouille,8.0,G,150000000.0,206435493.0,111.0,Animation|Comedy|Family|Fantasy,Janeane Garofalo,John Ratzenberger,Brian Dennehy,Brad Bird,English,USA,2.35,2007.0
209,Rio 2,6.4,G,103000000.0,131536019.0,101.0,Adventure|Animation|Comedy|Family|Musical,Miguel Ferrer,Rachel Crow,Jeffrey Garcia,Carlos Saldanha,English,USA,2.35,2014.0
238,"Monsters, Inc.",8.1,G,115000000.0,289907418.0,92.0,Adventure|Animation|Comedy|Family|Fantasy,Steve Buscemi,John Ratzenberger,James Coburn,Pete Docter,English,USA,1.85,2001.0
277,The Princess and the Frog,7.1,G,105000000.0,104374107.0,97.0,Animation|Family|Fantasy|Musical|Romance,Oprah Winfrey,Jenifer Lewis,Anika Noni Rose,Ron Clements,English,USA,1.85,2009.0
297,The Hunchback of Notre Dame,6.9,G,100000000.0,100117603.0,91.0,Animation|Drama|Family|Musical|Romance,Demi Moore,Jason Alexander,Bill Fagerbakke,Gary Trousdale,English,USA,1.78,1996.0
298,The Emperor's New Groove,7.3,G,100000000.0,89296573.0,78.0,Adventure|Animation|Comedy|Family|Fantasy,Eartha Kitt,Wendie Malick,John Fiedler,Mark Dindal,English,USA,1.66,2000.0
323,The Peanuts Movie,7.2,G,99000000.0,130174897.0,88.0,Adventure|Animation|Comedy|Family,Francesca Capaldi,Venus Schultheis,Bill Melendez,Steve Martino,English,USA,1.85,2015.0
338,Finding Nemo,8.2,G,94000000.0,380838870.0,100.0,Adventure|Animation|Comedy|Family,Alexander Gould,Stephen Root,Brad Garrett,Andrew Stanton,English,USA,1.85,2003.0
353,Toy Story 2,7.9,G,90000000.0,245823397.0,82.0,Adventure|Animation|Comedy|Family|Fantasy,Tom Hanks,John Ratzenberger,Wayne Knight,John Lasseter,English,USA,1.85,1999.0
362,Mulan,7.5,G,90000000.0,120618403.0,88.0,Adventure|Animation|Family|Fantasy|Musical|War,Ming-Na Wen,Harvey Fierstein,June Foray,Tony Bancroft,English,USA,1.66,1998.0
384,Rio,7.0,G,90000000.0,143618384.0,96.0,Adventure|Animation|Comedy|Family|Musical,Anne Hathaway,Wanda Sykes,Will.i.am,Carlos Saldanha,English,USA,2.35,2011.0
406,102 Dalmatians,4.8,G,85000000.0,66941559.0,100.0,Adventure|Comedy|Family,Ioan Gruffudd,Eric Idle,Jim Carter,Kevin Lima,English,USA,1.85,2000.0
444,Charlotte's Web,6.4,G,NaN,82506325.0,97.0,Comedy|Family|Fantasy,Steve Buscemi,Julia Roberts,Oprah Winfrey,Gary Winick,English,USA,1.85,2006.0
448,Alvin and the Chipmunks: Chipwrecked,4.4,G,75000000.0,133103929.0,87.0,Adventure|Animation|Comedy|Family|Fantasy|Music,Amy Poehler,Jesse McCartney,Lauren Gottlieb,Mike Mitchell,English,USA,1.85,2011.0
473,Spirit: Stallion of the Cimarron,7.0,G,80000000.0,73215310.0,83.0,Adventure|Animation|Family|Western,Matt Damon,Charles Napier,Zahn McClarnon,Kelly Asbury,English,USA,2.35,2002.0
480,Fantasia 2000,7.3,G,80000000.0,60507228.0,74.0,Animation|Family|Fantasy|Music,Quincy Jones,Penn Jillette,Russi Taylor,James Algar,English,USA,1.78,1999.0
500,Babe: Pig in the City,5.8,G,80000000.0,18318000.0,97.0,Adventure|Comedy|Drama|Family|Fantasy,Adam Goldberg,Elizabeth Daily,Glenne Headly,George Miller,English,Australia,1.85,1998.0
504,Oceans,7.8,G,40000000.0,19406406.0,104.0,Documentary|Drama,Pedro Armendáriz Jr.,Jacques Perrin,Rie Miyazawa,Jacques Perrin,French,France,2.35,2009.0
509,The Lion King,8.5,G,45000000.0,422783777.0,73.0,Adventure|Animation|Drama|Family|Musical,Matthew Broderick,Nathan Lane,Niketa Calame,Roger Allers,English,USA,1.66,1994.0
583,Cars,7.2,G,120000000.0,244052771.0,117.0,Adventure|Animation|Comedy|Family|Sport,John Ratzenberger,Cheech Marin,George Carlin,John Lasseter,English,USA,2.35,2006.0
657,The Santa Clause 2,5.5,G,60000000.0,139225854.0,104.0,Comedy|Family|Fantasy,Judge Reinhold,Aisha Tyler,Eric Lloyd,Michael Lembeck,English,USA,1.85,2002.0
714,Chicken Little,5.8,G,150000000.0,135381507.0,81.0,Adventure|Animation|Comedy|Family|Sci-Fi,Catherine O'Hara,Fred Willard,Amy Sedaris,Mark Dindal,English,USA,1.85,2005.0
756,The Tale of Despereaux,6.1,G,60000000.0,50818750.0,93.0,Adventure|Animation|Comedy|Family|Fantasy,Emma Watson,Matthew Broderick,Frank Langella,Sam Fell,English,UK,2.35,2008.0
839,Pocahontas,6.6,G,55000000.0,141600000.0,84.0,Adventure|Animation|Drama|Family|History|Music...,Christian Bale,Frank Welker,Irene Bedard,Mike Gabriel,English,USA,1.78,1995.0
902,Anastasia,7.1,G,50000000.0,58297830.0,94.0,Adventure|Animation|Drama|Family|Fantasy|Music...,Kirsten Dunst,Kelsey Grammer,Bernadette Peters,Don Bluth,English,USA,2.35,1997.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2913,The Land Before Time,7.3,G,12500000.0,48092846.0,69.0,Adventure|Animation|Family,Judith Barsi,Gabriel Damon,Bill Erwin,Don Bluth,English,USA,1.33,1988.0
2943,The Muppet Christmas Carol,7.7,G,12000000.0,27281507.0,89.0,Comedy|Drama|Family|Fantasy|Musical,Steven Mackintosh,Jerry Nelson,Steve Whitmire,Brian Henson,English,USA,1.85,1992.0
3028,High School Musical 3: Senior Year,4.5,G,11000000.0,90556401.0,112.0,Comedy|Drama|Family|Music|Musical|Romance,Lucas Grabeel,Matt Prokop,Corbin Bleu,Kenny Ortega,English,USA,1.85,2008.0
3079,2001: A Space Odyssey,8.3,G,12000000.0,56715371.0,161.0,Adventure|Mystery|Sci-Fi,Keir Dullea,Gary Lockwood,Glenn Beck,Stanley Kubrick,English,UK,2.20,1968.0
3101,The Longest Day,7.8,G,10000000.0,NaN,178.0,Action|Drama|History|War,Richard Burton,Richard Beymer,Eddie Albert,Ken Annakin,English,USA,2.35,1962.0
3107,Oliver!,7.5,G,10000000.0,16800000.0,153.0,Drama|Family|Musical,Oliver Reed,Ron Moody,Jack Wild,Carol Reed,English,UK,2.35,1968.0
3109,Recess: School's Out,6.5,G,23000000.0,36696761.0,82.0,Animation|Comedy|Family|Mystery|Sci-Fi,Diedrich Bader,Andrew Lawrence,Dabney Coleman,Chuck Sheetz,English,USA,1.85,2001.0
3142,Kit Kittredge: An American Girl,6.7,G,10000000.0,17655201.0,101.0,Drama|Family,Julia Ormond,Jane Krakowski,Willow Smith,Patricia Rozema,English,USA,1.85,2008.0
3179,The Straight Story,8.0,G,10000000.0,6197866.0,112.0,Biography|Drama,Sissy Spacek,Richard Farnsworth,Everett McGill,David Lynch,English,France,2.35,1999.0
3280,Fiddler on the Roof,8.0,G,9000000.0,50000000.0,181.0,Drama|Family|Musical|Romance,Topol,Paul Michael Glaser,Rosalind Harris,Norman Jewison,English,USA,2.35,1971.0
3356,The Muppet Movie,7.7,G,NaN,76657000.0,95.0,Adventure|Comedy|Family|Musical,Madeline Kahn,Jim Henson,Dom DeLuise,James Frawley,English,UK,1.85,1979.0
3359,The Sound of Music,8.0,G,8200000.0,163214286.0,174.0,Biography|Drama|Family|Musical|Romance,Eleanor Parker,Angela Cartwright,Nicholas Hammond,Robert Wise,English,USA,2.35,1965.0
3518,The Mighty Macs,6.5,G,7000000.0,1889522.0,99.0,Drama|Sport,Ellen Burstyn,Marley Shelton,Jennifer Butler,Tim Chambers,English,USA,2.35,2009.0
3563,The Andromeda Strain,7.2,G,6500000.0,NaN,115.0,Sci-Fi|Thriller,David Wayne,Paula Kelly,Eric Christmas,Robert Wise,English,USA,2.35,1971.0
3708,The Return of the Pink Panther,7.1,G,5000000.0,NaN,113.0,Comedy|Crime|Mystery,Burt Kwouk,Herbert Lom,Catherine Schell,Blake Edwards,English,UK,2.35,1975.0
3723,Doug's 1st Movie,5.0,G,5000000.0,19421271.0,77.0,Animation|Comedy|Family,Frank Welker,Constance Shulman,Alice Playten,Maurice Joyce,English,USA,1.33,1999.0
3970,Gone with the Wind,8.2,G,3977000.0,198655278.0,226.0,Drama|History|Romance|War,Hattie McDaniel,George Reeves,Thomas Mitchell,Victor Fleming,English,USA,1.37,1939.0
4024,March of the Penguins,7.6,G,8000000.0,77413017.0,80.0,Documentary,Morgan Freeman,Sofie Gråbøl,Romane Bohringer,Luc Jacquet,French,France,1.85,2005.0
4062,Beneath the Planet of the Apes,6.1,G,3000000.0,NaN,95.0,Action|Adventure|Sci-Fi,Linda Harrison,Gregory Sierra,Victor Buono,Ted Post,English,USA,2.35,1970.0
4064,Pokémon 3: The Movie,5.6,G,16000000.0,NaN,93.0,Action|Adventure|Animation|Family|Fantasy|Sci-Fi,Veronica Taylor,Eric Stuart,Lisa Ortiz,Kunihiko Yuyama,Japanese,Japan,1.85,2000.0
4093,Willy Wonka & the Chocolate Factory,7.8,G,3000000.0,NaN,89.0,Family|Fantasy|Musical,Peter Ostrum,Jack Albertson,Julie Dawn Cole,Mel Stuart,English,USA,1.33,1971.0
4162,The Black Stallion,7.4,G,2700000.0,NaN,118.0,Adventure|Family|Sport,Teri Garr,Kelly Reno,Hoyt Axton,Carroll Ballard,English,USA,1.85,1979.0
4185,Escape from the Planet of the Apes,6.3,G,2500000.0,NaN,98.0,Action|Sci-Fi,Roddy McDowall,M. Emmet Walsh,Sal Mineo,Don Taylor,English,USA,2.35,1971.0
4225,Fantasia,7.8,G,2280000.0,76400000.0,120.0,Animation|Family|Fantasy|Music,Leopold Stokowski,Deems Taylor,NaN,James Algar,English,USA,1.37,1940.0
4362,Battle for the Planet of the Apes,5.5,G,1800000.0,NaN,96.0,Action|Sci-Fi,Roddy McDowall,Paul Williams,Claude Akins,J. Lee Thompson,English,USA,2.35,1973.0
4427,Modern Times,8.6,G,1500000.0,163245.0,87.0,Comedy|Drama|Family,Paulette Goddard,Stanley Blystone,Fred Malatesta,Charles Chaplin,English,USA,1.37,1936.0
4591,A Lego Brickumentary,6.8,G,1000000.0,100240.0,93.0,Documentary,G.W. Krauss,Brian Whitaker,Jason Bateman,Kief Davidson,English,Denmark,NaN,2014.0
4725,Benji,6.1,G,500000.0,39552600.0,86.0,Adventure|Family|Romance,Frances Bavier,Peter Breck,Edgar Buchanan,Joe Camp,English,USA,1.85,1974.0
4787,Rise of the Entrepreneur: The Search for a Bet...,8.2,G,450000.0,NaN,52.0,Documentary,Bob Proctor,Jack Canfield,Eric Worre,Joe Kenemore,English,USA,NaN,2014.0
4874,Sunday School Musical,2.5,G,NaN,NaN,93.0,Drama|Musical,Dustin Fitzsimons,Mark Hengst,Debra Lynn Hull,Rachel Goldenberg,English,USA,1.85,2008.0

## Basic functions

There's a couple super helpful functions that help us work with our data.

For sorting, we can use `.sort_values(by= )`, and pass in either a single string, or multiple strings in a list.
<br>To flip the default order, change the `ascending= ` parameter to `False`

In [50]:
movies.sort_values(by=['imdb_score','gross'], ascending=False).head()

,movie_title,imdb_score,content_rating,budget,gross,duration,genres,actor_1_name,actor_2_name,actor_3_name,director_name,language,country,aspect_ratio,title_year
2765,Towering Inferno,9.5,NaN,NaN,NaN,65.0,Comedy,Martin Short,Andrea Martin,Joe Flaherty,John Blanchard,English,Canada,1.33,NaN
1937,The Shawshank Redemption,9.3,R,25000000.0,28341469.0,142.0,Crime|Drama,Morgan Freeman,Jeffrey DeMunn,Bob Gunton,Frank Darabont,English,USA,1.85,1994.0
3466,The Godfather,9.2,R,6000000.0,134821952.0,175.0,Crime|Drama,Al Pacino,Marlon Brando,Robert Duvall,Francis Ford Coppola,English,USA,1.85,1972.0
2824,Dekalog,9.1,TV-MA,NaN,447093.0,55.0,Drama,Krystyna Janda,Olaf Lubaszenko,Olgierd Lukaszewicz,NaN,Polish,Poland,1.33,NaN
3207,Dekalog,9.1,TV-MA,NaN,447093.0,55.0,Drama,Krystyna Janda,Olaf Lubaszenko,Olgierd Lukaszewicz,NaN,Polish,Poland,1.33,NaN

We could also use the `.value_counts()` function to could how many observations there are for each category.
<br>If we wanted relative frequencies (i.e. proportions) instead of absolute counts, we could change the `normalize=` parameter to `True`

In [55]:
movies.country.value_counts(normalize=True).head()

USA        0.755657
UK         0.088924
France     0.030568
Canada     0.025010
Germany    0.019254
Name: country, dtype: float64

Finally, we can take basic summary measures, like the `.mean()` or `.sum()` of a column.

In [67]:
movies.budget.mean()

39752620.436387606

## Chaining

Chaining helps make our code more concise and readable.

For example, if we wanted to combine some subsets with functions:

In [60]:
df1 = movies[movies.imdb_score > 8.5]
df2 = df1[df1.content_rating == 'PG']
df3 = df2.sort_values(by='duration',ascending=False)
df3.head()

,movie_title,imdb_score,content_rating,budget,gross,duration,genres,actor_1_name,actor_2_name,actor_3_name,director_name,language,country,aspect_ratio,title_year
2051,Star Wars: Episode V - The Empire Strikes Back,8.8,PG,18000000.0,290158751.0,127.0,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Kenny Baker,Anthony Daniels,Irvin Kershner,English,USA,2.35,1980.0
2373,Spirited Away,8.6,PG,19000000.0,10049886.0,125.0,Adventure|Animation|Family|Fantasy,Bunta Sugawara,Ryûnosuke Kamiki,Miyu Irino,Hayao Miyazaki,Japanese,Japan,1.85,2001.0
3024,Star Wars: Episode IV - A New Hope,8.7,PG,11000000.0,460935665.0,125.0,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Peter Cushing,Kenny Baker,George Lucas,English,USA,2.35,1977.0
4049,It's a Wonderful Life,8.6,PG,3180000.0,NaN,118.0,Drama|Family|Fantasy|Romance,Donna Reed,Lionel Barrymore,Thomas Mitchell,Frank Capra,English,USA,1.37,1946.0
4526,Casablanca,8.6,PG,950000.0,NaN,82.0,Drama|Romance|War,Humphrey Bogart,Claude Rains,Conrad Veidt,Michael Curtiz,English,USA,1.37,1942.0

We could instead write the above as:

In [59]:
movies[movies.imdb_score > 8.5].loc[movies.content_rating == 'PG'].sort_values(by='duration',ascending=False).head()

,movie_title,imdb_score,content_rating,budget,gross,duration,genres,actor_1_name,actor_2_name,actor_3_name,director_name,language,country,aspect_ratio,title_year
2051,Star Wars: Episode V - The Empire Strikes Back,8.8,PG,18000000.0,290158751.0,127.0,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Kenny Baker,Anthony Daniels,Irvin Kershner,English,USA,2.35,1980.0
2373,Spirited Away,8.6,PG,19000000.0,10049886.0,125.0,Adventure|Animation|Family|Fantasy,Bunta Sugawara,Ryûnosuke Kamiki,Miyu Irino,Hayao Miyazaki,Japanese,Japan,1.85,2001.0
3024,Star Wars: Episode IV - A New Hope,8.7,PG,11000000.0,460935665.0,125.0,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Peter Cushing,Kenny Baker,George Lucas,English,USA,2.35,1977.0
4049,It's a Wonderful Life,8.6,PG,3180000.0,NaN,118.0,Drama|Family|Fantasy|Romance,Donna Reed,Lionel Barrymore,Thomas Mitchell,Frank Capra,English,USA,1.37,1946.0
4526,Casablanca,8.6,PG,950000.0,NaN,82.0,Drama|Romance|War,Humphrey Bogart,Claude Rains,Conrad Veidt,Michael Curtiz,English,USA,1.37,1942.0

This works because each part of our code `returns` a dataframe, so we can keep tagging along functions instead of saving each step into a temporary variable.

**Try it out:** In one line, see if you can find the value counts of `content_rating` for movies with a gross revenue (`gross`) over `200000000` ($ 200 million)

In [22]:
movies[movies.gross > 200000000].content_rating.value_counts()

PG-13    97
PG       49
R        11
G        10
Name: content_rating, dtype: int64

# Practice w/ UFOs

Data sampled from the National UFO Reporting Center (NUFORC)
<br>With your breakout groups, open up `ufo.csv` and answer the following questions:

1. Among the West Coast states (California, Oregon, and Washington), how long (on average) did the fireballs encounters last?
2. Which state saw the most encounters that lasted between 5 minutes to 1 hour?
3. There was one particularly interesting encounter on `2/11/2004 00:00` in West Palm Beach, Florida. What happened?

<br>Hint: Break down each question into parts, and chain them back together. There's no particular 'right' way
<br>To refer to the `shape` column, use `ufo['shape']` instead of `ufo.shape`, since the latter is a reserved attribute

In [61]:
ufo = pd.read_csv('ufo.csv')
ufo.head()

,datetime,city,state,country,shape,duration_sec,duration_hrs,comments,latitude,longitude
0,1/25/2014 22:00,tewksbury,ma,us,light,4.0,00:04,Green and red falling light over walgreens res...,42.610556,-71.234722
1,8/20/2004 22:27,lake in the hills,il,us,triangle,180.0,2-3 minutes,On August 20&#442004 at exactly 10:25 to 10:27...,42.181667,-88.330278
2,1/23/2009 19:00,slidell,la,us,sphere,7200.0,2 hours,Bright red&#44 green &#44 white and blue spher...,30.275000,-89.781111
3,12/15/1994 21:00,alliance,oh,us,formation,1800.0,30 min +,Brightly Colored Orbs Over Portage County,40.915278,-81.106111
4,7/31/2011 21:00,milford,ct,us,oval,15.0,10-15 seconds,Bright orange&#44 silent orb&#44 moving steadi...,41.222222,-73.056944

In [73]:
# 1
ufo.loc[ufo.state.isin(['ca','or','wa'])].loc[ufo['shape']=='fireball'].duration_sec.mean()

238.88888888888889

In [74]:
# 2
ufo.loc[(ufo.duration_sec>=5*60) & (ufo.duration_sec<=60*60)].state.value_counts().head(1)

ca    392
Name: state, dtype: int64

In [75]:
# 3
ufo.loc[ufo.datetime == '2/11/2004 00:00'].loc[ufo.city=='west palm beach'].comments.values[0]

'BLINDING LIGHT LIFTED MY DOG AND TOOK OFF INTO SPACE'

# Groupby Objects

From before, we used `value_counts()` to get the number of movies per each content rating?

In [77]:
movies.content_rating.value_counts()

R            2118
PG-13        1461
PG            701
Not Rated     116
G             112
Unrated        62
Approved       55
TV-14          30
TV-MA          20
X              13
TV-PG          13
TV-G           10
Passed          9
NC-17           7
GP              6
M               5
TV-Y            1
TV-Y7           1
Name: content_rating, dtype: int64

This is a good summary statistic to examine the distribution of our dataset. But...

<br>What if we want to know how movie performance differs by rating?
<br>We need to apply some function (i.e. take the mean of revenue) **per each** content rating

In [79]:
movies_byRating = movies.groupby('content_rating')
type(movies_byRating)

pandas.core.groupby.groupby.DataFrameGroupBy

This creates a special **GroupBy object**. 

<br>For now, let's think of it like a *collection* of dataframes, seperated by each unique value from content rating (One group for `R`, `PG-13`, etc).
<br>We can't easily render what the entire GroupBy object looks like, but we can pull out a particular group

In [80]:
movies_byRating

In [81]:
print(type(movies_byRating.get_group('PG')))
movies_byRating.get_group('PG').head()

<class 'pandas.core.frame.DataFrame'>

,movie_title,imdb_score,content_rating,budget,gross,duration,genres,actor_1_name,actor_2_name,actor_3_name,director_name,language,country,aspect_ratio,title_year
7,Tangled,7.8,PG,260000000.0,200807262.0,100.0,Adventure|Animation|Comedy|Family|Fantasy|Musi...,Brad Garrett,Donna Murphy,M.C. Gainey,Nathan Greno,English,USA,1.85,2010.0
9,Harry Potter and the Half-Blood Prince,7.5,PG,250000000.0,301956980.0,153.0,Adventure|Family|Fantasy|Mystery,Alan Rickman,Daniel Radcliffe,Rupert Grint,David Yates,English,UK,2.35,2009.0
16,The Chronicles of Narnia: Prince Caspian,6.6,PG,225000000.0,141614023.0,150.0,Action|Adventure|Family|Fantasy,Peter Dinklage,Pierfrancesco Favino,Damián Alcázar,Andrew Adamson,English,USA,2.35,2008.0
33,Alice in Wonderland,6.5,PG,200000000.0,334185206.0,108.0,Adventure|Family|Fantasy,Johnny Depp,Alan Rickman,Anne Hathaway,Tim Burton,English,USA,1.85,2010.0
38,Oz the Great and Powerful,6.4,PG,215000000.0,234903076.0,130.0,Adventure|Family|Fantasy,Tim Holmes,Mila Kunis,James Franco,Sam Raimi,English,USA,2.35,2013.0

When we apply **aggregation** functions to a `GroupBy` object, we get back averages for each column in the dataframe, **broken down** by content rating

In [82]:
movies_byRating.agg('mean')

,imdb_score,budget,gross,duration,aspect_ratio,title_year
content_rating,,,,,,
Approved,7.325455,4.142475e+06,4.814586e+07,116.218182,1.735818,1954.781818
G,6.529464,4.499913e+07,8.245516e+07,98.973214,1.962523,1995.892857
GP,6.916667,5.550000e+06,4.380000e+07,110.833333,2.024000,1970.666667
M,6.840000,4.700000e+06,6.255445e+07,114.600000,2.012000,1968.400000
NC-17,6.542857,7.940714e+06,4.476870e+06,102.000000,1.855714,1994.571429
Not Rated,6.631034,4.479213e+06,2.090037e+06,110.318966,2.101739,1997.504348
PG,6.294437,4.838956e+07,7.295273e+07,104.857347,2.061250,2000.392297
PG-13,6.257495,5.425734e+07,6.564854e+07,111.365068,2.151456,2005.710472
Passed,7.166667,3.031421e+06,1.100354e+07,115.222222,1.351111,1941.222222
R,6.527101,3.364755e+07,2.998365e+07,108.781767,2.118677,2002.950425
TV-14,7.250000,3.640000e+06,NaN,52.551724,8.683103,2012.666667
TV-G,6.920000,3.670000e+06,NaN,62.400000,2.023333,1997.500000
TV-MA,8.250000,3.400000e+07,4.470930e+05,47.350000,7.652632,NaN
TV-PG,7.353846,3.200000e+06,NaN,50.384615,4.492500,2010.333333
TV-Y,7.400000,NaN,NaN,30.000000,1.330000,NaN
TV-Y7,7.200000,NaN,NaN,30.000000,4.000000,NaN
Unrated,6.920968,5.092971e+06,4.302599e+06,102.790323,2.110370,1990.354839
X,6.500000,3.338462e+06,1.865881e+07,92.615385,1.928462,1981.307692

If we were just to apply `.mean()` to the entire dataframe, we'd only get back one row with summaries for the entire dataset

In [87]:
pd.DataFrame(movies.mean(), columns=['Total']).T

,imdb_score,budget,gross,duration,aspect_ratio,title_year
Total,6.442138,3.975262e+07,4.846841e+07,107.201074,2.220403,2002.470517

We've got other ways to aggregate the data too.

Here, we're showing the mean, max, and min values of `imdb_score` by passing in multiple strings in a list to `.agg()`

In [88]:
movies_byRating['imdb_score'].agg(['mean', 'max', 'min', 'count'])

                    mean  max  min  count
content_rating
Approved        7.325455  8.9  4.1     55
G               6.529464  8.6  1.6    112
GP              6.916667  8.0  6.2      6
M               6.840000  8.1  6.0      5
NC-17           6.542857  7.6  4.6      7
Not Rated       6.631034  8.9  2.0    116
PG              6.294437  8.8  1.7    701
PG-13           6.257495  9.0  1.9   1461
Passed          7.166667  8.1  6.3      9
R               6.527101  9.3  1.9   2118
TV-14           7.250000  8.7  3.3     30
TV-G            6.920000  8.4  4.8     10
TV-MA           8.250000  9.1  7.0     20
TV-PG           7.353846  8.4  5.5     13
TV-Y            7.400000  7.4  7.4      1
TV-Y7           7.200000  7.2  7.2      1
Unrated         6.920968  8.7  3.2     62
X               6.500000  7.9  4.0     13

The results of these groupby operations are all dataframes, check it out with the `type( )` operator
This means we can start chaining together dataframe functions, for example `sort_values()`

**Try it out:** Break down median revenues by country, and sort them highest to lowest
<br> If you finish early, try to show the same thing as above, but now *exclude* countries with less than 30 movies

In [73]:
# 1
movies.groupby(by='country').agg('median').sort_values(by='gross', ascending=False).head()

,imdb_score,budget,gross,duration,aspect_ratio,title_year
country,,,,,,
Taiwan,7.15,15000000.0,64340682.0,112.5,1.86,2007.5
Peru,5.40,45000000.0,57362581.0,110.0,1.85,1994.0
South Africa,6.25,17500000.0,45089048.0,100.5,1.85,2011.5
USA,6.50,20000000.0,32178777.0,103.0,1.85,2005.0
New Zealand,7.30,25000000.0,30465398.0,108.0,2.35,2005.0

In [93]:
# 2
df = movies.groupby(by='country')['gross'].agg(['median', 'count']).sort_values(by='median', ascending=False)
df[df['count'] >= 30].reset_index()

# Note that we had to save the dataframe first to easily access the new indices for the mask/filter
# Also note that when we aggregated with multiple conditions, we first specified the column to aggregate on
# What happens if we didn't (i.e. first groupby, then aggregate, and filter columns last)? Try it out

     country      median  count
0        USA  32178777.0   3235
1    Germany  20978074.5     88
2  Australia  17356110.0     42
3         UK  13401683.0    364
4     Canada   6854620.0     72
5     France   4291965.0    121

### Multilevel GroupBy

We can also group on multiple columns to get *all unique combinations* of those columns. 

<br> For example, we can see if the relationship between `content_rating` and `imdb_rating` differs across countries by using both as keys

In [94]:
movies_byCountryRating = movies.groupby(['country', 'content_rating'])

In [63]:
movies_byCountryRating['imdb_score'].agg('mean').sort_values(ascending=False).head()

country     content_rating
Poland      TV-MA             9.1
Italy       Approved          8.9
Kyrgyzstan  PG-13             8.7
Italy       TV-MA             8.7
            PG-13             8.6
Name: imdb_score, dtype: float64

# Summary

That's it for now!

<br>Today you learned how to:
- **Import** a dataset as a pandas object
- Check out quick features, like `.head()`, `.shape`, and `.value_counts()`
- The distinction between `pd.Series` and `pd.DataFrame` objects
- **Filter** rows based on some condition
- **Subset** columns to those we want

We also used special `GroupBy` objects to get specific drill-down insights by:
<br>(1) first breaking out, or **grouping** a dataset based on some category, then
<br>(2) **aggregating** information from each observation in that category

<br> In practice, if we wanted to get a mean score, broken down by every value in a given column, we would do:
<br>`df.groupby(by='group column').agg('mean').score_column`