# Lab 03 - Let's explore the data from the intro survey!
Start by importing the necessary libraries (pandas)

In [ ]:
# Import the necessary libraries
import pandas as pd

Next, let's read in the data. This time, we'll be working with two csv files. Make sure to name them different things!

URL1: `https://raw.githubusercontent.com/ishaandey/node/master/week-3/lab/survey_responses.csv`
<br>URL2: `https://raw.githubusercontent.com/ishaandey/node/master/week-3/lab/survey_names.csv`

In [ ]:
# Read in the data from both csv files
df1 = pd.read_csv("https://raw.githubusercontent.com/ishaandey/node/master/week-3/lab/survey_responses.csv")
df2 = pd.read_csv("https://raw.githubusercontent.com/ishaandey/node/master/week-3/lab/survey_names.csv")

Let's see what's in the data we just imported

In [ ]:
# Check out both DataFrames
df1.head()

         Timestamp  ...                              Hobbies I have are...
0  2/14/2021 10:16  ...                                      Dance, baking
1  2/14/2021 10:25  ...                               Outdoors activities
2  2/14/2021 11:01  ...                     Video games, tv, sports, anime
3  2/14/2021 11:22  ...  Ultimate Frisbee, Biking (Road and Mountain), ...
4  2/14/2021 12:07  ...  I'm a dancer, I enjoy trying different cuisine...

[5 rows x 15 columns]

In [ ]:
df2.head()

   Index First name Last name Preferred name / Nickname (if different)
0      1   Susannah     White                                    Susie
1      2        PII       PII                                      NaN
2      3   Jackson       Wolf                                      NaN
3      4        PII       PII                                      NaN
4      5       Paul   Andrews                                      NaN

It looks like the data is all from the same form, but the name columns got separated from the rest of the info. Merge the two dataframes

In [ ]:
# Merge on the Index column
df = pd.merge(df1, df2, on='Index', how='outer')

Now we have all the data together. Let's get some more info about the columns of the dataframe

In [ ]:
# Get info from the dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 15 entries, 0 to 14
Data columns (total 18 columns):
 #   Column                                                                                                             Non-Null Count  Dtype
---  ------                                                                                                             --------------  -----
 0   Timestamp                                                                                                          15 non-null     object
 1   Index                                                                                                              15 non-null     int64
 2   Can we use your responses to this form for a class activity? (Data sharing is restricted to only your classmates)  15 non-null     object
 3   What college are you in? (If not UVA, put in your school)                                                          12 non-null     object
 4   What year are you?                                                                                                 15 non-null     object
 5   My planned (or declared) major is... (Separate each by commas)                                                     15 non-null     object
 6   I'm new to CS                                                                                                      15 non-null     object
 7   How I feel about...  [Python]                                                                                      15 non-null     object
 8   How I feel about...  [R]                                                                                           15 non-null     object
 9   How I feel about...  [SQL]                                                                                         15 non-null     object
 10  How I feel about...  [SAS / STATA]                                                                                 15 non-null     object
 11  How I feel about...  [Other Languages]                                                                             14 non-null     object
 12  How I feel about...  [Statistics]                                                                                  15 non-null     object
 13  Topics I'm interested in exploring with data science ...                                                           12 non-null     object
 14  Hobbies I have are...                                                                                              15 non-null     object
 15  First name                                                                                                         15 non-null     object
 16  Last name                                                                                                          15 non-null     object
 17  Preferred name / Nickname (if different)                                                                           2 non-null      object
dtypes: int64(1), object(17)
memory usage: 2.2+ KB

You'll notice that from the previous step, all of the columns are objects except Index. Let's change that and make the Index column a column of strings instead of integers

In [ ]:
# Convert the Index column from ints to Strings
df['Index'] = df.Index.astype(str)

In [ ]:
# See the changes by looking at the dataframe info again
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 15 entries, 0 to 14
Data columns (total 18 columns):
 #   Column                                                                                                             Non-Null Count  Dtype
---  ------                                                                                                             --------------  -----
 0   Timestamp                                                                                                          15 non-null     object
 1   Index                                                                                                              15 non-null     object
 2   Can we use your responses to this form for a class activity? (Data sharing is restricted to only your classmates)  15 non-null     object
 3   What college are you in? (If not UVA, put in your school)                                                          12 non-null     object
 4   What year are you?                                                                                                 15 non-null     object
 5   My planned (or declared) major is... (Separate each by commas)                                                     15 non-null     object
 6   I'm new to CS                                                                                                      15 non-null     object
 7   How I feel about...  [Python]                                                                                      15 non-null     object
 8   How I feel about...  [R]                                                                                           15 non-null     object
 9   How I feel about...  [SQL]                                                                                         15 non-null     object
 10  How I feel about...  [SAS / STATA]                                                                                 15 non-null     object
 11  How I feel about...  [Other Languages]                                                                             14 non-null     object
 12  How I feel about...  [Statistics]                                                                                  15 non-null     object
 13  Topics I'm interested in exploring with data science ...                                                           12 non-null     object
 14  Hobbies I have are...                                                                                              15 non-null     object
 15  First name                                                                                                         15 non-null     object
 16  Last name                                                                                                          15 non-null     object
 17  Preferred name / Nickname (if different)                                                                           2 non-null      object
dtypes: object(18)
memory usage: 2.2+ KB

It looks like the column names are super long, which could be a problem down the line. Let's shorten them. So you don't have to write out a new name for each column, here's a list of new column names:

'timestamp', 'index', 'anonymous', 'college', 'year', 'major', 'cs_new', 'python_feel', 'r_feel', 'sql_feel', 'sas_feel', 'other_languages_feel', 'stats_feel', 'ds_interest', 'hobbies', 'first', 'last', 'nickname'

In [ ]:
# Get the column names
df.columns

Index(['Timestamp', 'Index',
       'Can we use your responses to this form for a class activity? (Data sharing is restricted to only your classmates)',
       'What college are you in? (If not UVA, put in your school)',
       'What year are you?',
       'My planned (or declared) major is... (Separate each by commas)',
       'I'm new to CS', 'How I feel about...  [Python]',
       'How I feel about...  [R]', 'How I feel about...  [SQL]',
       'How I feel about...  [SAS / STATA]',
       'How I feel about...  [Other Languages]',
       'How I feel about...  [Statistics]',
       'Topics I'm interested in exploring with data science ...',
       'Hobbies I have are...', 'First name', 'Last name',
       'Preferred name / Nickname (if different)'],
      dtype='object')

In [ ]:
# Rename them to something better
df.columns = ['timestamp', 'index', 'anonymous', 'college', 'year', 'major', 'cs_new', 'python_feel', 'r_feel', 'sql_feel', 'sas_feel', 'other_languages_feel', 'stats_feel', 'ds_interest', 'hobbies', 'first', 'last', 'nickname']

Take a look at the nicknames column. It seems like not that many people have nicknames. Let's find out exactly how many people don't have nicknames

In [ ]:
# How many people don't have nicknames
df.nickname.isna().size

15

To confuse Ishaan, the PCs decided to call everyone who doesn't have a preferred nickname Ishaan. Change the dataframe to reflect this.

In [ ]:
# Replace empty fields in the nickname column to Ishaan
df['nickname'] = df.nickname.fillna("Ishaan")

Some people forgot to fill out the college field. Let's assume they go to Virginia Tech (ew)

In [ ]:
# Assume that people who don't have a college go to Virginia Tech
df['college'] = df.college.fillna("VT :(")

Unfortunately, most colleges don't use the terms 1st year, 2nd year, 3rd year and 4th year. Make the data more accessible by changing the year data to freshman, sophomore, junior and senior (leave graduate school as is)

In [ ]:
# Change the year names to what the plebs(jk) call them
df['year'] = df.year.replace({"1st Year":"Freshman", "2nd Year":"Sophomore", "3rd Year": "Junior", "4th Year": "Senior"})

         timestamp index            anonymous  ...     first     last nickname
0  2/14/2021 10:16     1                Sure!  ...  Susannah    White    Susie
1  2/14/2021 10:25     2  Yes, but anonymized  ...       PII      PII   Ishaan
2  2/14/2021 11:01     3                Sure!  ...  Jackson      Wolf   Ishaan
3  2/14/2021 11:22     4  Yes, but anonymized  ...       PII      PII   Ishaan
4  2/14/2021 12:07     5                Sure!  ...      Paul  Andrews   Ishaan

[5 rows x 18 columns]

Let's see how many people are CS majors. Unfortunately, people wrote in both CS and Computer Science. Check out the pandas documentation to see how you can check for both in the same line:

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.contains.html

In [ ]:
# Find out how students many are CS majors
df.major.str.contains('CS|Computer Science')

0     False
1     False
2      True
3     False
4     False
5      True
6     False
7     False
8      True
9      True
10     True
11    False
12    False
13    False
14     True
Name: major, dtype: bool

It looks like a lot of people are doing 2 majors! Find out exactly how many students are double majoring

In [ ]:
# Find out how many people are doing more than one major
df.major.str.split(', ').apply(lambda x: len(x) > 1).sum()

5

Pandas has a super cool object called datetime objects. Let's experiment with them a bit. First convert the timestamp column to datetime objects

In [ ]:
# Convert the timestamps to datetime objects
df.timestamp = pd.to_datetime(df.timestamp)

Take a look at the features of the datetime objects. Use the day in the object to find out how many people spend their Valentine's day filling out this form

In [ ]:
# Find out how many people spent their Valentine's Day filling this form out
df[df.timestamp.dt.day == 14].shape[0]

14

Now try figuring out how many people submitted the form before noon

In [ ]:
# Find out how many people submitted before noon
df[df.timestamp.dt.hour < 12].shape[0]

4